---
name: "Build"

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: h3r3t1c-overlays
          authToken: '${{ secrets.CACHIX_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix build .#packages.x86_64-linux.clickup
      - run: nix build .#packages.x86_64-linux.loco-cli
      - run: nix build .#packages.x86_64-linux.zed

